version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-local
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dataplatform
      POSTGRES_PASSWORD: dataplatform
      POSTGRES_DB: dataplatform
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=en_US.UTF-8'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataplatform"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: