postgres_transform:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dataplatform') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'dataplatform') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dataplatform') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
    
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      
  target: dev